// Rewrite the instructions in your own words

// Write the objectives and the tests

// Write the pseudocode



// paste your JS generated by blockly below here

var x, y, z, a, b, c, result, Alphabeth, Input, i, j, tempo;


x = 'x';
y = 'y';
z = 'z';
a = 'a';
b = 'b';
c = 'c';
result = '';
Alphabeth = 'a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z'.split(',');
Input = window.prompt('Insert the text').split('');
for (var i_index in Input) {
  i = Input[i_index];
  for (var j_index in Alphabeth) {
    j = Alphabeth[j_index];
    if (i == j) {
      if (i == a) {
        tempo = x;
        result += String(tempo);
        break;
      }
      if (i == b) {
        tempo = y;
        result += String(tempo);
        break;
      }
      if (i == c) {
        tempo = z;
        result += String(tempo);
        break;
      }
      tempo = Alphabeth[(((Alphabeth.indexOf(i) + 1) - 3) - 1)];
      result += String(tempo);
      break;
    }
  }
}
window.alert(result);