// Rewrite the instructions in your own words

// Write the objectives and the tests

// Write the pseudocode



// paste your JS generated by blockly below here

var Email_Input, List_first, A, List_Second, B, C, X, Y, i, test, test1;


Email_Input = window.prompt('Input the email');
List_first = Email_Input.split('@');
A = List_first[0];
List_Second = List_first.slice(-1)[0].split('.');
B = List_Second[0];
C = List_Second.slice(-1)[0];
X = 'gmail,hotmail,yahoo'.split(',');
Y = 'com,it,et,org,fr,us'.split(',');
for (var i_index in X) {
  i = X[i_index];
  if (i == B) {
    test = 0;
    break;
  }
}
for (var i_index2 in Y) {
  i = Y[i_index2];
  if (i == C) {
    test1 = 0;
    break;
  }
}
if (test == 0 && test1 == 0) {
  window.alert('valid');
} else {
  window.alert('Invalid');
}
