// Rewrite the instructions in your own words

// Write the objectives and the tests

// Write the pseudocode



// paste your JS generated by blockly below here

var input, list, Acronyms, j;


input = window.prompt('insert the phrase:');
list = input.split(' ');
Acronyms = '';
for (var j_index in list) {
  j = list[j_index];
  Acronyms += String(j.charAt(0));
}
Acronyms = Acronyms.toUpperCase();
window.alert(Acronyms);
