// Rewrite the instructions in your own words




// Write the objectives and the tests

// Write the pseudocode

//Start
// Accept words (Rock, Scissor, paper) from user
//Randomly select one of this
//compare the recieved and generated
//Repeat this three times
//Evaluate the result of the game at the end of the third look
//Give the result(Win or loose) to the user
//Finish


// paste your JS generated by blockly below here

var A, ed, B, random, guess, x, win, loose, hit, rc;

function mathRandomInt(a, b) {
  if (a > b) {
    // Swap a and b to ensure a is smaller.
    var c = a;
    a = b;
    b = c;
  }
  return Math.floor(Math.random() * (b - a + 1) + a);
}


ed = '-';
A = 'Rock,Scissor,Paper';
B = A.split(',');
win = 0;
loose = 0;
for (var count = 0; count < 3; count++) {
  x = mathRandomInt(1, 3);
  if (B[(x - 1)] == window.prompt('play')) {
    win = (typeof win == 'number' ? win : 0) + 1;
  } else {
    loose = (typeof loose == 'number' ? loose : 0) + 1;
  }
}
hit = 'you lose ';
rc = 'Good Job! you will: ';
if (win > loose) {
  window.alert(rc + win + ed + loose);
} else {
  window.alert(hit + win + ed + loose);
}
